sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: '1234'
  alioss:
    access-key-id: LTAI5tQn62FgUU85LXdkQQka
    access-key-secret: oV532za93BM7ccALSREQkqnWajPPoB
    bucket-name: web-chop
    endpoint: oss-cn-hangzhou.aliyuncs.com